### ISSUE TITLE
After run test, not show execption

### ISSUE THREAD

**Issue by ganjarsetia** [inspector-apm/inspector-laravel#12]
I'm using Laravel 5.8 and `"inspector-apm/inspector-laravel": "^4.4"`
after following install instruction https://docs.inspector.dev/laravel/installation

I'm running command `php artisan inspector:test`
here the result

![image](https://user-images.githubusercontent.com/3258090/78889392-c5755580-7a8d-11ea-91e6-cf4489abeec8.png)

but in inspector dashboard, it doesn't show anything.

Is there something wrong?

maybe it's a DNS problem, but what domain should I check?
Here I tried ping some domains

![image](https://user-images.githubusercontent.com/3258090/78890007-09b52580-7a8f-11ea-9dd9-50e0f2052f52.png)

**Comment by ilvalerione** [comment]
Hi, you can try to ping our ingetion API at: https://ingest.inspector.dev

**Comment by ganjarsetia** [comment]
> Hi, you can try to ping our ingetion API at: https://ingest.inspector.dev

yeah sure

![image](https://user-images.githubusercontent.com/3258090/78891407-b5f80b80-7a91-11ea-81dc-6acfae93462c.png)

**Comment by ilvalerione** [comment]
Are you using a VM as development environment (like Homestead or similar)?

**Comment by ganjarsetia** [comment]
nope, its production server

**Comment by ilvalerione** [comment]
Timeout error should means that your server isn't able to reach our system.

Ask your host if there a firewall or security modules (e.g. mod_security ) that could block the outgoing cURL requests.

**Comment by ganjarsetia** [comment]
yes I know we can't reach your system. But its not showing any errors, just warning and `Done! Explore your data on https://app.inspector.dev` I believe it should show error before that. Also I can ping your domains. So this is wrong, don't show success message, when the app can't reach Inspector.

We use firewall. Only port 80 & 443 is allowed.

**Comment by ilvalerione** [comment]
I apologize for the unclear message. It will be reviewed to avoid misunderstandings. 

The package simply try to send data to `https://ingest.inspector.dev` at the standard port `80`.  There aren't any particular settings in data sending. You can check the source code for more details: https://github.com/inspector-apm/inspector-php/blob/master/src/Transport/CurlTransport.php

**Comment by ganjarsetia** [comment]
Ah its ok. No worries. Sorry if I rude to you. I'm not used to speak English.

I'll try to debug your code in server, maybe there is something I can make it work. I really need APM tools.

**Comment by ganjarsetia** [comment]
may I know why this issue is closed? It still problem, which is can't send data to Inspector and the success message is still showing before error.

**Comment by ilvalerione** [comment]
It's a normal behavior. Data transfer is the last operation by design.

The problem should be why your server can't communicate with our API, but this seams a problem by your side.

Are you able to send data to Inspector from your local machine?

**Comment by ganjarsetia** [comment]
I'll try to send it, do you have simple PHP script to test send data to Inpector without composer? So I just put my API Key and execute it in shell

**Comment by ilvalerione** [comment]
You can use the basic PHP version instead of laravel specific integration: https://github.com/inspector-apm/inspector-php

Take a look on our official documentation to understand how use it: https://docs.inspector.dev/php

**Comment by ganjarsetia** [comment]
I tried that, but its not easy to use. Like I said, I hope test send data without composer :)

Now I solve the problem, by changing value timeout in this line.

`curl_setopt($handle, CURLOPT_CONNECTTIMEOUT, 60);`
` curl_setopt($handle, CURLOPT_TIMEOUT, 60);`

**Comment by ilvalerione** [comment]
60 seconds is a really high threshold. It means that your application should wait up to 1 minute before end its execution.

This isn't an acceptable value for most applications. 

I really invite you to identify the problem that causes a so slow connection between your server and an external endpoint.

**Comment by ganjarsetia** [comment]
Which one shouldn't 60 ?
Now I change to
```
curl_setopt($handle, CURLOPT_CONNECTTIMEOUT, 10);
curl_setopt($handle, CURLOPT_TIMEOUT, 10);
``` 

It works, but the app is so slow. If I disable it, it run fast again.

**Comment by ilvalerione** [comment]
It sounds strange, the data transfer starts after your application sent the response to the client. So it can require seconds to be accomplished, but it is totally transparent from your client point of view (other machines, or the browser).

Anyway current thresholds in the package are serving thousends of applications.

I really invite you to investigate to identify the problem that causes a so slow connection between your application and an external endpoint.
