### ISSUE TITLE
 Argument 1 passed to Inspector\Configuration::setEnabled() must be of the type boolean, null given, called in vendor/inspector-apm/inspector-laravel/src/InspectorServiceProvider.php on line 69

### ISSUE THREAD

**Issue by conorwatt1** [inspector-apm/inspector-laravel#14]
**Describe the bug**
When running composer require inspector-apm/inspector-laravel it fails with the above error but still installs the vendor folder and updates composer.json. But the error still occurs when running php artisan config:cache

**To Reproduce**
1. composer require inspector-apm/inspector-laravel
2. See error

1. php artisan config:cache
2. see error

**Screenshots**
[
![Screenshot from 2020-07-30 10-51-11](https://user-images.githubusercontent.com/26536725/88937855-ad029400-d252-11ea-9a3b-acaafa80fa34.png)
](url)

![Screenshot from 2020-07-30 10-54-28](https://user-images.githubusercontent.com/26536725/88938166-0f5b9480-d253-11ea-906b-2a7737489440.png)

**Web (please complete the following information):**
 - Package Version 4.4
 - Laravel 7

**Comment by ilvalerione** [comment]
Hi @conorwatt1,
thank you for posting!

You could try clearing the Laravel configuration before installing the package:

- Remove the package from the vendor folder, and remove the entry line in the composer file;
- Clear the app configuration like: `php artisan clear:config`;
- Install the package: `composer require inspector-apm/inspector-laravel`;
- Than you could cache the configuration again: `php artisan config:cache`;

Let me know if these steps solves the issue.
