### ISSUE TITLE
Command line is too long in windows

### ISSUE THREAD

**Issue by darkrevenger** [inspector-apm/inspector-laravel#15]
Inspector is working like a charm on linux, but on windows where the max command line is @8200 chars the inspector:test (and any error) won't be submitted via api since the CMD states "Command line is too long"
![image](https://user-images.githubusercontent.com/15086662/91873282-35f45d00-ec4f-11ea-8d5d-3dade5aa21eb.png)

Since echo %path% shows that only the path is about 2k chars (and it is needed to be set with all of those paths so shortening it is not a solution) it would be lovely if there was a way to set up curl in some custom way this package could use it or get it that avoided this horrible problem windows will never fix since they don't care and want to force users to do short paths.

I don't know if its useful but I found a stackoverflow that might help solving this problem https://stackoverflow.com/questions/682799/what-to-do-with-the-input-line-is-too-long-error-message?noredirect=1&lq=1 by using double quotation when calling a command.

**Comment by ilvalerione** [comment]
Hi @darkrevenger, to avoid this behavior you could try to change the inspector transport configuration fields from "async" to "sync". 

It will change the way the package send data to our inspection API using php curl extension. This is not an optimal solution in terms of performance, but locally it couldn't be a problem.

You can change this settings using INSPECTOR_TRANSPORT=sync in your environment file to apply this configuraiton only in your local environment, so in production it continues to work as usual.

Let me know if this solution solves your issue.

**Comment by ilvalerione** [comment]
Hi @darkrevenger, in the latest package version we solved this issue dividing the payload in smaller chunk in case of window system.

**Comment by darkrevenger** [comment]
Thanks you Valerio! Great support, congratulations for the great product you're doing here.

**Comment by ilvalerione** [comment]
Thank you for your words!

**Comment by CarlaGramichi** [comment]
Hello, 
when executing my job I get 'Command line too long'. I changed the configuration in my environment variables and after executing the job again, the execution is not reflected in the inspector. Might you help me?!

**Comment by ilvalerione** [comment]
Hi @CarlaGramichi are using the INSPECTOR_TRANSPORT=sync in the environment file?

**Comment by CarlaGramichi** [comment]
Hello, I tried both ways: first I left it async in config/inspector and it gives me ''command line too long'. And then in the environment file INSPECTOR_TRANSPORT=sync. In both cases, the execution of the job is not reflected in the Inspector.

**Comment by ilvalerione** [comment]
Can you send us more details about your project:

- Version of Laravel
- Version of the Inspector package you have installed
- Version of the PHP

**Comment by CarlaGramichi** [comment]
Yes, the versions are as follows:

- Version of Laravel: 7.30.6
- Version of PHP: 7.2.19 
- Version of the Inspector package you have installed: 4.7.20

**Comment by ilvalerione** [comment]
@CarlaGramichi can you send us the email you used to register your account on Inspector? 

We can move this conversation to email at support@inspector.dev than I'll eventually publish here the solution if it can be relevant for other users.

Send us your account information at support@inspector.dev

**Comment by CarlaGramichi** [comment]
@ilvalerione, I just sent my information to the mail support@inspector.dev

**Comment by CarlaGramichi** [comment]
Hello @ilvalerione , any news on the subject?
