### ISSUE TITLE
Inspector:test fails with the new version.

### ISSUE THREAD

**Issue by darkrevenger** [inspector-apm/inspector-laravel#16]
Edit to clarify: This is on windows. If I have to do some extra steps please let me know.
It looks like a typo on a braket is caussing it.
![image](https://user-images.githubusercontent.com/15086662/93388565-49074f80-f841-11ea-8a20-cd61ab7a460d.png)

Here is another similar mistake tried on another repo.
![image](https://user-images.githubusercontent.com/15086662/93607098-43c01700-f99f-11ea-99c4-24ed343f26b9.png)

**Comment by ilvalerione** [comment]
Hi @darkrevenger, what version fo window?

**Comment by darkrevenger** [comment]
Windows 10 pro version.
