### ISSUE TITLE
Transaction discrepancy in mail/inspector.dev?

### ISSUE THREAD

**Issue by darkrevenger** [inspector-apm/inspector-laravel#18]
If I'm understunding something wrong please let me know.

Background: Recently I've been attacked by hackers so I'm kinda paranoid that my servers are still infected.
The mailing transaction count read this:
![image](https://user-images.githubusercontent.com/15086662/121023061-4ce55400-c779-11eb-98f7-7f88dd5af326.png)

But when I enter into my inspector.dev project to see them I found that the numbers are not even close to the one on the mail.
![image](https://user-images.githubusercontent.com/15086662/121023290-84ec9700-c779-11eb-84fd-bf6e5cf36c10.png)

Do I have to activate something or is inspector working improperly?

This is a test server so having thousand of transactions makes no sense.

**Comment by ilvalerione** [comment]
Hi, thank you for your report, it was an intetal bug of the platform rwlated to a wrong query against our analytics datastore.

Anyway you should consider the dashboard the ultimate source of truth.

Thank you for your alert, we are actively working to fix the issue.
