### ISSUE TITLE
Issue in GateServiceProvider.php right after install

### ISSUE THREAD

**Issue by Gab-Metzger** [inspector-apm/inspector-laravel#20]
Hi everyone,

I just installed the **inspector-laravel** package into my Laravel API (v5.8.38).
I followed the documentation but right after all steps done I'm having the follower error:

`Argument 1 passed to Inspector\Laravel\Providers\GateServiceProvider::beforeGateCheck() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of Api\Models\Entities\Eloquent\User given, called in /**/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 473`.

In file `/**/vendor/inspector-apm/inspector-laravel/src/Providers/GateServiceProvider.php`.

For now I didn't load any middleware but as I understand from the documentation, this is not mandatory.

Am I doing something wrong?

Many thanks,
Gabriel

**Comment by ilvalerione** [comment]
Hi Gabriel,
Thank you for your report. 

The GateServiceProvider is loaded regardless of the middleware.

I need to check thr Laravel documentation for 5.8 to adjust the callback parameter.

I'll give you a feedback soon.

Best,
Valerio

**Comment by ilvalerione** [comment]
@Gab-Metzger I published a new release (4.7.8) that contains the fix for this issue. You should update your composer dependencies to get the latest version.

**Comment by Gab-Metzger** [comment]
@ilvalerione Thank you very much, I'll give it a try right now and keep you updated.

**Comment by Gab-Metzger** [comment]
Everything is workin great! Thank you so much 👍
