### ISSUE TITLE
Undefined property: Inspector\Laravel\Inspector::$transaction

### ISSUE THREAD

**Issue by felippeduarte** [inspector-apm/inspector-laravel#21]
**Describe the bug**
Inspector randomly throws this error

**To Reproduce**
Cant' find a way to reproduce. Seems this error occurs when running scheduled jobs.

**Expected behavior**
Not thrown any error

**Screenshots**
-

**Web (please complete the following information):**
 - Package Version 4.7.2
 - Laravel / Lumen version 7.30.4

**Additional context**
```
Undefined property: Inspector\Laravel\Inspector::$transaction File ../vendor/inspector-apm/inspector-php/src/Inspector.php Line 109
#0  ..vendor/inspector-apm/inspector-php/src/Inspector.php(109): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1  ..vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Inspector\Inspector->currentTransaction()
#2  ..vendor/inspector-apm/inspector-laravel/src/Providers/JobServiceProvider.php(121): Illuminate\Support\Facades\Facade::__callStatic()
#3  ..vendor/inspector-apm/inspector-laravel/src/Providers/JobServiceProvider.php(65): Inspector\Laravel\Providers\JobServiceProvider->handleJobEnd()
#4  ..vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(381): Inspector\Laravel\Providers\JobServiceProvider->Inspector\Laravel\Providers\{closure}()
#5  ..vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#6  ..vendor/laravel/framework/src/Illuminate/Queue/Worker.php(540): Illuminate\Events\Dispatcher->dispatch()
#7  ..vendor/laravel/framework/src/Illuminate/Queue/Worker.php(392): Illuminate\Queue\Worker->raiseExceptionOccurredJobEvent()
#8  ..vendor/laravel/framework/src/Illuminate/Queue/Worker.php(360): Illuminate\Queue\Worker->handleJobException()
#9  ..vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#10 ../vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#11 ../vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#12 ../vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#13 ../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#14 ../vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 ../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 ../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#17 ../vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#18 ../vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#19 ../vendor/symfony/console/Command/Command.php(288): Illuminate\Console\Command->execute()
#20 ../vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#21 ../vendor/symfony/console/Application.php(974): Illuminate\Console\Command->run()
#22 ../vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand()
#23 ../vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#24 ../vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#25 ../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#26 ../artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#27 {main}
```

**Comment by ilvalerione** [comment]
Hi @felippeduarte , thank you for your report. First you should update your composer dependencies because you are using an old version (4.7.2) instead of the latest (4.7.13).

Just a `composer update` is needed to get the latest version.

Let me know if the problem persist also after the update.

**Comment by felippeduarte** [comment]
Updated to 4.7.13 and still getting this error

**Comment by ilvalerione** [comment]
I reproduced the error in my test environment. It happens in case of failed jobs. I'll release the fix soon.

**Comment by ilvalerione** [comment]
@felippeduarte the new release `4.7.14` fix the issue. Let us know if you stumble onto other strange behaviours. 

Thanks for your collaboration.

**Comment by felippeduarte** [comment]
This new release seems to fixed the issue. Thanks.

**Comment by anaxamaxan** [comment]
I was getting this error in 4.7.16. I used `<server name="INSPECTOR_ENABLE" value="false"/>` in my phpunit.xml to suppress Inspector during testing.

**Comment by ilvalerione** [comment]
@anaxamaxan  Does the stack trace of your error pass through the `Inspector\Laravel\Providers\JobServiceProvider`?

**Comment by myusufid** [comment]
I have the same error

```Undefined property: Inspector\\Laravel\\Inspector::$transaction (SQL: insert into `queue_monitor` (`job_id`, `name`, `queue`, `started_at`, `started_at_exact`, `attempt`, `updated_at`, `created_at`) values (QkmynkLpgHA8d16rMZEM3sO1FinFoEiq, App\\Jobs\\SendEmail, default, 2021-12-07 06:00:04, 2021-12-07 06:00:04.506027, 1, 2021-12-07 06:00:04, 2021-12-07 06:00:04))```

**Comment by TimOrangetalent** [comment]
I still got the same error.
```
ErrorException in ../vendor/inspector-apm/inspector-php/src/Inspector.php at line 115
Undefined property: Inspector\Laravel\Inspector::$transaction
```

I have the issue in the jobs. After the second job is finished.

- Package Version 4.7.16
- Laravel 8.79.0

**Comment by ilvalerione** [comment]
Hi @TimOrangetalent, is it happens running unit tests or during normal operation?

**Comment by TimOrangetalent** [comment]
@ilvalerione It happens on a normal operation.

**Comment by ilvalerione** [comment]
I made other tests to verify the consistency of the code, but it seams quite solid based on job events: https://github.com/inspector-apm/inspector-laravel/blob/master/src/Providers/JobServiceProvider.php#L50

Perhaps other details of your app implementation can be helpful. 

- What is your worker configuration in the enviroment where the error happen?
- What is your queue driver?

Any other details you consider relevant.

**Comment by TimOrangetalent** [comment]
I'm testing on my local version (Valet). My Queue driver is set to `sync`.
But when i change the queue driver to `redis`, it seems to run correctly.

So i revert everything and set the queue driver back to `sync`. It looks like the jobs are running normal, without the error.
Maybe it's like a caching problem? (But i must say, i cleared all the caches and still got the error message before my redis change)

**Comment by ilvalerione** [comment]
Where you schedule the job? is it during an http request, in an artisan command?

**Comment by ilvalerione** [comment]
The sync driver isn't used in a production environment, but this fix will guarantee a best experience also for anyone test the package in a local environment as happened to you.

Let me know if you find other issues. Thank you for your contribution.

**Comment by TimOrangetalent** [comment]
Thanks for your replay and the fix. The error is gone. 
However, the monitor doesn't seem to be working for the command/jobs now.

When i visit the site, i see all kinds of results on the monitor page. But when the command start, it doesn't seem to be monitoring like it did before.

And you are correct, in production we use the `redis` queue. But for the local version, we also use the `sync` queue.

**Comment by TimOrangetalent** [comment]
Oke, thanks for your explanation!
