### ISSUE TITLE
v4.7.19 throwing errors 

### ISSUE THREAD

**Issue by Sammyjo20** [inspector-apm/inspector-laravel#24]
Hi there,

Thanks for building Inspector, it's great! I went to upgrade Inspector today and we're now getting this error, we're running Laravel 8. It looks like something that was [introduced in 4.7.19. ](https://github.com/inspector-apm/inspector-laravel/compare/4.7.18...4.7.19)

These are happening in our tests even though the Inspector key was not specified.

![Screen Shot 2022-02-18 at 08 38 20](https://user-images.githubusercontent.com/29132017/154647678-24a1af44-827a-4943-a7e2-678d273d1e75.png)

**Comment by ilvalerione** [comment]
Hi Sam,
Thank you for reporting the issue to us. I'm investigating.

**Comment by ilvalerione** [comment]
Hi @Sammyjo20 the new version 4.7.20 solve this issue.

**Comment by Sammyjo20** [comment]
Hey @ilvalerione thanks for solving so quickly!
