### ISSUE TITLE
Question: What happens if Inspector goes down?

### ISSUE THREAD

**Issue by Sammyjo20** [inspector-apm/inspector-laravel#29]
Does Inspector temporarily disable itself if it detects a flurry of "5xx" errors from your server? I've noticed when disabling inspector, the response times are a lot faster. Is there an option to run reporting on queue?

**Comment by ilvalerione** [comment]
Hi Sam, Inspector sends the data to the remote system asynchronously. It launch a process that deliver the data in background: 
https://github.com/inspector-apm/inspector-php/blob/master/src/Transports/AsyncTransport.php#L72

There is no a queuing system by default. It can be implemented as a custom Transport class.

We have made a few attempts in the past. But they required using files on the filesystem, which is even worse in terms of performance. In addition to the risks of taking up space on the physical disk of the servers.

Data collection instead is executed during normal execution and it is the only thing that can impact real performance of your code. Usually this work is negligible.

**Comment by Sammyjo20** [comment]
Great! Thanks for the reply.

I do notice however when enabling Inspector locally it will increase the time it takes for my responses to come back. For example, the average request time locally is roughly 30ms. When I enable inspector even with the default synchronous mode, it can range anywhere between 40 and 120ms per request, usually around the 80ms range.

**Comment by ilvalerione** [comment]
Are you using a Linux virtual machine for local development or are you working on the OS (win, mac)?

**Comment by Sammyjo20** [comment]
Working directly on the Mac with Laravel Valet

**Comment by ilvalerione** [comment]
it could behave a little different working on the underlying OS. It depends by the number of character supported by the terminal, and other limits that do not exist in the production VM.
