### ISSUE TITLE
Deprecation Warning on Laravel 9 / PHP 8.1

### ISSUE THREAD

**Issue by BryanYeh** [inspector-apm/inspector-laravel#31]
I am getting this deprecation warning. Is there a fix or not to show this warning?

`Return type of Inspector\Models\Arrayable::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/forge/matchbacks.tkmkt.com/vendor/inspector-apm/inspector-php/src/Models/Arrayable.php on line 137`

 - Package Version : 4.7.23
 - Laravel : 9.15.0
 - PHP : 8.1

**Comment by ilvalerione** [comment]
Hi @BryanYeh, it is related to the underalying package inspector-apm/inspector-php.

The warning was suppressed with the latest version 3.7.14. The warning should disappear after updating your composer dependencies.

In this article you can learn more about the deprecation warning: https://php.watch/versions/8.1/internal-method-return-types
