### ISSUE TITLE
Package doesn't save a log context.

### ISSUE THREAD

**Issue by zozulinskyi** [inspector-apm/inspector-laravel#35]
**Describe the bug**
Hi. Thanks for beautiful package but I have some problems with default logger helper.

If I use for example this:
`logger()->info(message: 'Executed: [app:orders:cancel]', context: ['count' => $count]);`

I can't see the context data in my Inspector panel. After analyse the package i found next code: [click](https://github.com/inspector-apm/inspector-laravel/blob/65145480719fe93962fa49b03dcef724a0a42129/src/Providers/ExceptionsServiceProvider.php#L60)
Maybe we can add log context here or there are other reasons why the context is not available?

**To Reproduce**
1. Create console command
2. Use default logger call
3. Watch to Inspector panel [screenshot](https://snipboard.io/3jTk4F.jpg)

After add context to compact function I can see my log fully and this behaviour i expected. [screenshot](https://snipboard.io/kD6M7E.jpg)

**Web (please complete the following information):**
 - PHP: 8.1
 - Package Version: 4.7.28
 - Laravel Version: 9.46.0

**Comment by ilvalerione** [comment]
Hi @zozulinskyi, you can add context to the current transaction.

```php
inspector()->transaction()->addContext("label", ["foo" => "bar"]);
```

You will see a new tab directly in the transaction panel details.

**Comment by zozulinskyi** [comment]
@ilvalerione it's work for me, thx.
