### ISSUE TITLE
Can't Install on laravel 5.8 

### ISSUE THREAD

**Issue by vladles** [inspector-apm/inspector-laravel#4]
Hello,
when I tried to install your package on the laravel 5.8 

`composer require inspector-apm/inspector-laravel`
get error: 

Your requirements could not be resolved to an installable set of packages.

  

> Problem 1
>     - inspector-apm/inspector-laravel 2.4.1 requires inspector-apm/inspector-php dev-develop -> satisfiable by inspector-apm/inspector-php[dev-develop] but these conflict with your requirements or minimum-stability.
>     - inspector-apm/inspector-laravel 2.4.0 requires inspector-apm/inspector-php dev-develop -> satisfiable by inspector-apm/inspector-php[dev-develop] but these conflict with your requirements or minimum-stability.
>     - Installation request for inspector-apm/inspector-laravel ^2.4 -> satisfiable by inspector-apm/inspector-laravel[2.4.0, 2.4.1].

My composer.json config
`{
    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "minimum-stability": "dev",
        "prefer-stable": true
    }
}
`

**Comment by ilvalerione** [comment]
Hi, thank you for report, I just published the new version with dependencies fix.
