### ISSUE TITLE
MAX_POST_LENGTH issue

### ISSUE THREAD

**Issue by hiteshbansal81** [inspector-apm/inspector-laravel#43]
**Describe the bug**
Getting error on memory size

**Expected behavior**
Not to break operation

**Screenshots**
PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 16777248 bytes) in /vendor/maennchen/zipstream-php/src/File.php on line 332

   Symfony\Component\ErrorHandler\Error\FatalError

  Allowed memory size of 805306368 bytes exhausted (tried to allocate 16777248 bytes)

  at vendor/maennchen/zipstream-php/src/File.php:332
    328▕                 ($this->exactSize ?? PHP_INT_MAX) - $this->uncompressedSize,
    329▕                 self::CHUNKED_READ_BLOCK_SIZE
    330▕             );
    331▕
  ➜ 332▕             $data = fread($this->unpackStream(), $readLength);
    333▕
    334▕             hash_update($hash, $data);
    335▕
    336▕             $this->uncompressedSize += strlen($data);

PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 20185088 bytes) in /vendor/inspector-apm/inspector-php/src/Transports/AbstractApiTransport.php on line 127

**Web**
 - Console Command
 - 4.8
 - Laravel 10

**Comment by ilvalerione** [comment]
Hi @hiteshbansal81 are you reporting custom data using "addContext()" method during the transaction or for custom segments?

**Comment by hiteshbansal81** [comment]
Hello @ilvalerione 

Apologies for the delay in response

I was utilizing a default configuration of the inspector for reporting. Essentially, when I disabled the inspector, I received an error due to a memory issue from PHP. It was at this point that I could debug the code I had written for my custom task.

**Allow me to outline how I reproduced the issue:**

My task involved exporting data from a table in the format of an xlsx file. Each Excel file was intended to contain at least 4000 rows with 6 columns. However, upon attempting to export the data into xlsx format, I encountered the following issue

```
PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1155072 bytes) in /home/sites-staging-scrapper/htdocs/scrapper.sites-staging.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php on line 97

   Symfony\Component\ErrorHandler\Error\FatalError

  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1155072 bytes)

  at vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:97
     93▕      */
     94▕     protected function getCommand(array $data)
     95▕     {
     96▕         if (str_starts_with($data['command'], 'O:')) {
  ➜  97▕             return unserialize($data['command']);
     98▕         }
     99▕
    100▕         if ($this->container->bound(Encrypter::class)) {
    101▕             return unserialize($this->container[Encrypter::class]->decrypt($data['command']));


   Whoops\Exception\ErrorException

  Allowed memory size of 805306368 bytes exhausted (tried to allocate 1155072 bytes)

  at vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:97
     93▕      */
     94▕     protected function getCommand(array $data)
     95▕     {
     96▕         if (str_starts_with($data['command'], 'O:')) {
  ➜  97▕             return unserialize($data['command']);
     98▕         }
     99▕
    100▕         if ($this->container->bound(Encrypter::class)) {
    101▕             return unserialize($this->container[Encrypter::class]->decrypt($data['command']));

      +1 vendor frames

  2   [internal]:0
      Whoops\Run::handleShutdown()
```

Initially, I suspected the error to be originating from the Inspector Package. However, after disabling the Inspector Package, I identified the actual issue.

I trust that you will investigate the matter and ensure that your package does not return its own failure method. It would be preferable to return the actual DOM error so that we can debug and rectify it effectively.
