### ISSUE TITLE
Argument #1 ($transaction) must be of type Inspector\Models\Transaction, null given

### ISSUE THREAD

**Issue by muhammedshiffin** [inspector-apm/inspector-laravel#44]
**Describe the bug**
Inspector\Models\Segment::__construct(): Argument #1 ($transaction) must be of type Inspector\Models\Transaction, null given, called in /home/623427.cloudwaysapps.com/yntumwxmfn/public_html/vendor/inspector-apm/inspector-php/src/Inspector.php on line 195

**To Reproduce**
No sure, how to reproduce this, but here's my code snippet:
```
catch (\Throwable $th) {
    DB::rollBack();

    inspector()->reportException($th);
}
```

**Web (please complete the following information):**
 - Browser: Chrome
 - Package Version: 4.7.x
 - Laravel: 10.x

**Comment by ilvalerione** [comment]
Hi @muhammedshiffin are you using INSPECTOR_ENABLE=false environment variable?
