### ISSUE TITLE
Ability to change `curlPath` for AsyncTransport

### ISSUE THREAD

**Issue by tomykho** [inspector-apm/inspector-laravel#48]
**Is your feature request related to a problem? Please describe.**
[Official Documentaion for Laravel Vapor](https://docs.inspector.dev/guides/laravel/laravel-vapor) mentioned Inspector requires two natives PHP functions ([proc_open](https://www.php.net/manual/en/function.proc-open.php), [proc_close](https://www.php.net/manual/en/function.proc-close.php)) to send monitoring data to the remote API. But Laravel Vapor PHP runtime layers didn't [disable_functions proc_open and proc_close](https://github.com/laravel/vapor-php-build/blob/master/php83al2/runtime/php.ini#L31), Instead of [curl](https://github.com/laravel/vapor-php-build/blob/master/php83al2/php.Dockerfile#L170) binary are actually built and installed at different path.

**Describe the solution you'd like**
Add `curlPath` and `certPath` for `config/inspector.php`

**Additional context**
Custom Transport for Inspector to work with Laravel Vapor without Docker and Queue.
```php
<?php

namespace App\Transports;

use Inspector\Transports\AsyncTransport;

class VaporAsyncTransport extends AsyncTransport
{
    protected $curlPath = '/opt/bin/curl';

    protected function buildCurlCommand($data): string
    {
        $curl = parent::buildCurlCommand($data);
        $curl .= ' --cacert /opt/lib/curl/cert.pem';
        return $curl;
    }
}
```

**Comment by ilvalerione** [comment]
Hi @tomykho, the package already has an option for this configuration: 

https://github.com/inspector-apm/inspector-laravel/blob/master/config/inspector.php#L73

To access this configuration property you should publish the inspector configu file: 

`php artisan vendor:publish --provider="Inspector\Laravel\InspectorServiceProvider"`

Furthermore you must be sure to have the underlying php package at the latest version 3.8.3
You should update composer dependencies (composer update) before using this option.

**Comment by ilvalerione** [comment]
@tomykho Are proc_close and proc_open functions enabled by default in the default Vapor runtime?

When I built this package they weren't. If you tried using the default Vapor configuration without any other customizations I could update the documentation to reflect this opportunity for other users.

Are any other configurations needed to the Vapor runtime layers?

**Comment by tomykho** [comment]
> @tomykho Are proc_close and proc_open functions enabled by default in the default Vapor runtime?
> 
> When I built this package they weren't. If you tried using the default Vapor configuration without any other customizations I could update the documentation to reflect this opportunity for other users.
> 
> Are any other configurations needed to the Vapor runtime layers?

I am using [this repo](https://github.com/laravel/vapor-php-build) to build custom Vapor runtime layers (with updated [packages](https://github.com/laravel/vapor-php-build/blob/master/php83al2/versions.ini) without extra customization), because I thought I could use that instead of using Docker.
I will help you try it on default Vapor runtime and give you updates here later.

**Comment by tomykho** [comment]
It also works on the Vapor default runtime.
Is it possible to remove this deprecation warning?
```
PHP Deprecated:  Creation of dynamic property Inspector\Transports\AsyncTransport::$curlPath is deprecated in /vendor/inspector-apm/inspector-php/src/Transports/AbstractApiTransport.php on line 52
```

**Comment by ilvalerione** [comment]
I released a patch: https://github.com/inspector-apm/inspector-php/releases/tag/3.8.4

You can get it updating composer dependencies (composer update).
