### ISSUE TITLE
Property Inspector\Laravel\Views\ViewEngineDecorator::$lastCompiled does not exist

### ISSUE THREAD

**Issue by jobins-devs** [inspector-apm/inspector-laravel#49]
**Describe the bug**
The error message `Property Inspector\Laravel\Views\ViewEngineDecorator::$lastCompiled does not exist` is encountered, indicating that the `lastCompiled` property is missing or undefined.

**To Reproduce**
1. Go to a specific view within the Laravel application.
2. Perform an action that triggers the view rendering error page.
3. Observe the error `Property Inspector\Laravel\Views\ViewEngineDecorator::$lastCompiled does not exist`.

**Expected behavior**
The view should be rendered correctly without any missing properties, and the page should load as expected.

**Screenshots**

**Web (please complete the following information):**
- Browser: Chrome, Safari
- Package Version: 4.9
- Laravel 8

**Additional context**
This error occurs in the `Inspector\Laravel\Views\ViewEngineDecorator` class, specifically when trying to access a non-existent property `lastCompiled`. It seems to be related to the view rendering engine.

Stack trace
```
Sep 24 10:31:01 laravel php: [2024-09-24 10:31:01] production.ERROR: Property Inspector\Laravel\Views\ViewEngineDecorator::$lastCompiled does not exist {"userId":255,"exception":"[object] (ReflectionException(code: 0): Property Inspector\\Laravel\\Views\\ViewEngineDecorator::$lastCompiled does not exist at /home/user/laravel/vendor/spatie/laravel-ignition/src/Views/ViewExceptionMapper.php:128)
Sep 24 10:31:01 laravel php: #0 /home/user/laravel/vendor/spatie/laravel-ignition/src/Views/ViewExceptionMapper.php(128): ReflectionProperty->__construct()
Sep 24 10:31:01 laravel php: #1 /home/user/laravel/vendor/spatie/laravel-ignition/src/Views/ViewExceptionMapper.php(115): Spatie\\LaravelIgnition\\Views\\ViewExceptionMapper->getKnownPaths()
Sep 24 10:31:01 laravel php: #2 /home/user/laravel/vendor/spatie/laravel-ignition/src/Views/ViewExceptionMapper.php(67): Spatie\\LaravelIgnition\\Views\\ViewExceptionMapper->findCompiledView()
Sep 24 10:31:01 laravel php: #3 /home/user/laravel/vendor/spatie/laravel-ignition/src/Views/ViewExceptionMapper.php(46): Spatie\\LaravelIgnition\\Views\\ViewExceptionMapper->createException()
Sep 24 10:31:01 laravel php: #4 /home/user/laravel/vendor/spatie/laravel-ignition/src/IgnitionServiceProvider.php(213): Spatie\\LaravelIgnition\\Views\\ViewExceptionMapper->map()
Sep 24 10:31:01 laravel php: #5 /home/user/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(369): Spatie\\LaravelIgnition\\IgnitionServiceProvider->Spatie\\LaravelIgnition\\{closure}()
Sep 24 10:31:01 laravel php: #6 /home/user/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(221): Illuminate\\Foundation\\Exceptions\\Handler->mapException()
Sep 24 10:31:01 laravel php: #7 /home/user/laravel/app/Exceptions/Handler.php(86): Illuminate\\Foundation\\Exceptions\\Handler->report()
Sep 24 10:31:01 laravel php: #8 /home/user/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\\Exceptions\\Handler->report()
Sep 24 10:31:01 laravel php: #9 /home/user/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Pipeline->handleException()
Sep 24 10:31:01 laravel php: #24 /home/user/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
Sep 24 10:31:01 laravel php: #25 /home/user/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()```

**Comment by ilvalerione** [comment]
What version of the spatie/laravel-ignition package have you installed?

**Comment by jobins-devs** [comment]
> What version of the spatie/laravel-ignition package have you installed?

  "spatie/laravel-ignition": "^1.6" 
  "laravel/framework": "^8.78.0"

**Comment by ilvalerione** [comment]
I suppose it is what is declared in the composer.json file. But I need to know the real version currently installed in your app: 1.6.4, 1.7.x, etc..

**Comment by jobins-devs** [comment]
> I suppose it is what is declared in the composer.json file. But I need to know the real version currently installed in your app: 1.6.4, 1.7.x, etc..

Laravel Version: 8.83.26
spatie/laravel-ignition Version: 1.6.1

Steps to Reproduce:
1. Create a simple Blade view that uses a few variables.
2. Do not pass these variables from the controller.
3. The described issue will occur under these conditions.

**Comment by ilvalerione** [comment]
What version of `guzzlehttp/guzzle` is installed in your app?

**Comment by jobins-devs** [comment]
[composer.txt](https://github.com/user-attachments/files/17505396/composer.txt)

I have uploaded lock file for future reference 

"name": "guzzlehttp/guzzle",
 "version": "7.5.0",

**Comment by ilvalerione** [comment]
What version of PHP ?

**Comment by jobins-devs** [comment]
we are using php 8.0

**Comment by ilvalerione** [comment]
PHP 8 is not compatible with Laravel 8. How did you do it?

**Comment by jobins-devs** [comment]
> PHP 8 is not compatible with Laravel 8. How did you do it?

Laravel 9 is the last version to be compatible with php 8.

https://github.com/laravel/laravel/blob/9.x/composer.json#L8

**Comment by ilvalerione** [comment]
You said me that your application is on Laravel 8. Laravel 8 it's not compatible with "spatie/laravel-ignition 1.6.1". I con't reproduce your issue.
