### ISSUE TITLE
REQUEST_METHOD not found when starting transaction by WebRequestMonitoring

### ISSUE THREAD

**Issue by GeorgeDevol** [inspector-apm/inspector-laravel#51]
**Describe the bug**
While unit testing I got the exception REQUEST_METHOD in the constructor of the Request class. It is the same bug as #45, but I'm not using Octane/Swoole in my app. I just extend the TestCase class.

It started when I updated my project to laravel 11 (from 10).

I did already 2 days of debugging but I could not find a proper fix. I created a DummyJob (it does nothing) and if I dispatch it. The bug does not occur because the startTransaction() in WebRequestMonitoring is not called.

**To Reproduce**
Difficult to reproduce. I just updated all the packages to support laravel 11 and the error was thrown

**Expected behavior**
The Request class should not fail if the REQUEST_METHOD is not available. Or the server variables should be passed when the inspector transaction should start (WebRequestMonitoring middleware)

**Web (please complete the following information):**
All packages are updated to their lastest available version starting

 "php": "^8.2",
"ext-json": "*",
"ext-pdo": "*",
"guzzlehttp/guzzle": "^7.9.0",
"halaxa/json-machine": "^1.1",
"inspector-apm/inspector-laravel": "^4.7.0",
"laravel-json-api/laravel": "^v4.1",
"laravel/fortify": "^1.23",
"laravel/framework": "^v11.0",
"laravel/horizon": "^5.22",
"laravel/passport": "^12.0.0",
"laravel/sanctum": "^4.0",
"laravel/tinker": "^2.8",
"logtail/monolog-logtail": "^v3.2",
"predis/predis": "^2.2",
"sentry/sentry-laravel": "^4.9",
"spatie/laravel-data": "^4.11",
"spatie/laravel-permission": "^6.9",
"spatie/laravel-tags": "^4.6",
"stancl/tenancy": "^3.8",
"staudenmeir/laravel-cte": "^1.11"

**Additional context**

**Comment by ilvalerione** [comment]
Hi the issue depends by the basic PHP library behind the Laravel package. The latest release 3.8.8 should fix the problem.

You just need to update the composer dependencies to get the latest version of our libraries.

Let me know if you have any issue.
