### ISSUE TITLE
Only report unhandled exceptions

### ISSUE THREAD

**Issue by ariaieboy** [inspector-apm/inspector-laravel#52]
Hi, I want to know if it can only report unhandled exceptions to the inspector.
I disabled all the monitoring using the config file, but the commands get reported.

**Comment by ilvalerione** [comment]
You can add all your commands signatures to the ignore_commands property in the inspector.php configuration file. Consider that we provide a monitoring service, if you don't need to monitor why you want to use our product?

**Comment by ariaieboy** [comment]
Thanks for your reply
For ignoring URLs we can use wildcard expressions having wildcard expressions for commands can help a lot.

And about your second question, I don't need performance monitoring for now; I just want to monitor my unhandled errors.

**Comment by ilvalerione** [comment]
Wildcard for jobs and command are in the roadmap for the beginning of 2025.
