### ISSUE TITLE
 Does not record exceptions laravel 5.4

### ISSUE THREAD

**Issue by romaque** [inspector-apm/inspector-laravel#6]
I installed the library in laravel 5.4, when an error occurs does not register in inspector Exceptions

**Comment by ilvalerione** [comment]
Hi @romaque thank you for your report!

Laravel 5.4 doesn't have "package autodiscovery" feature, so after install the composer package you need to attach the InspectorServiceProvider and facade in your `config/app.php`

`
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        ...,

        \Inspector\Laravel\InspectorServiceProvider::class,
`

`
'aliases' => [
         ...,
        'Inspector' =>  \Inspector\Laravel\Facades\Inspector::class,
`

I hope this can help you

**Comment by romaque** [comment]
Hi @ilvalerione thank you so much solved my problem

**Comment by ilvalerione** [comment]
You're welcome! ;)
